---
always_allow_html: yes
output:
  md_document:
    variant: markdown_github
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# gaugeR

A function to create interactive gauge charts as well as output and render functions for using gauge within Shiny applications and interactive Rmd documents.

## Installation

```{r, echo = FALSE}
library(gaugeR)
```

You can install gaugeR from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("jumpingrivers/gaugeR")
```

## Example

This are some basic examples of the command `gauge()`:

```{r example}
gauge(0)
gauge(50)
gauge(c(3,3))
```

## Shiny Example

Here is a very basic shiny app example

```{r, eval = FALSE}
## Only run this in interactive sessions
if(interactive()){
  ui <- fluidPage(
    titlePanel("Gauge Example!"),
    sidebarLayout(
      sidebarPanel(
        sliderInput("obs",
                    "Pick a percentage",
                    min = 1,
                    max = 100,
                    value = 5)
      ),
      mainPanel(
        gaugeOutput("gaugePlot")
      )
    )
  )


  # Define the server code
  server <- function(input, output) {

    output$gaugePlot <- renderGauge({
      gauge(input$obs)
    })

  }

  shinyApp(ui = ui, server = server)
}
```
